name: facemind
description: "Project Year4"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_maps_flutter: ^2.5.0  # ✅ เวอร์ชันล่าสุด
  geolocator: ^10.1.0  # ✅ ใช้ดึงพิกัด GPS
  geocoding: ^2.1.0  # ✅ ใช้แปลงพิกัดเป็นที่อยู่
  flutter_google_places: ^0.3.0  # ✅ แทน google_places
  shared_preferences: ^2.2.0  # ✅ บันทึกข้อมูลแบบ Local
  permission_handler: ^11.0.1  # ✅ ใช้ขอสิทธิ์ GPS
  image_picker: ^1.0.4  # ✅ ใช้เลือกรูปภาพจากแกลเลอรี
  cupertino_icons: ^1.0.8  # ✅ รองรับไอคอน iOS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
